import type { Metadata } from "next"
import { Exo } from "next/font/google"
import "./globals.css"
import "@/lib/check-env"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const exo = Exo({
  weight: ["400"],
  subsets: ["latin"],
  variable: '--exo-font'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${exo.variable} antialiased scroll-smooth snap-y snap-proximity`}>
      <body className="bg-background text-foreground">
        {children}
      </body>
    </html>
  );
}
